### ISSUE TITLE
LICENSE coverage years seem off

### ISSUE THREAD

**Issue by jonassmedegaard** [kasei/atteanx-store-dbi#3]
LICENSE says 2014-2016, but seemingly innovation happened in 2016-2017, and again in 2020.

Makes sense to include earlier years if innovations happened before being tracked in git, but I suggest to extend coverage to also include more recent innovations.

**Comment by kasei** [comment]
I've fixed this, but also notice that the LICENSE file provides a different license than claimed in the code. I'll file a new issue for that.
